name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 30
          plugin_languages_recent_categories: data, markup, programming
          plugin_languages_sections: recently-used
          plugin_languages_details: lines, percentage
          plugin_languages_skipped: natgo/fabric-modpack natgo/natgo
          plugin_languages_aliases: TSX:TypeScript
          plugin_languages_ignored: smali, html, javascript, css, svg, json
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_skipped: natgo/natgo
          plugin_habits_facts: yes
          plugin_habits_charts: yes
